src/Entity/Actor.php
<?php

namespace App\Entity;

use App\Repository\ActorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ActorRepository::class)]
#[Vich\Uploadable]
class Actor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\ManyToMany(targetEntity: Program::class, inversedBy: 'actors')]
    private $programs;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $birth_date;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[Vich\UploadableField(mapping: 'actor_file', fileNameProperty: 'image')]
    #[Assert\File(
        maxSize: '2M',
        mimeTypes: ['image/jpeg', 'image/png', 'image/webp'])]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    public function __construct()
    {
        $this->programs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): ?string {
        $fullName = $this->getFirstname() .' '. $this->getLastname();
        return $fullName;
    }

    public function getBirthDate(): ?string
    {
        return $this->birth_date;
    }

    public function setBirthDate(?string $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return Collection<int, Program>
     */
    public function getPrograms(): Collection
    {
        return $this->programs;
    }

    public function addProgram(Program $program): self
    {
        if (!$this->programs->contains($program)) {
            $this->programs[] = $program;
        }

        return $this;
    }

    public function removeProgram(Program $program): self
    {
        $this->programs->removeElement($program);

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get the value of imageFile
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @return  self
     */ 
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
        if($imageFile){
            $this->createdAt = new \DateTimeImmutable();
        }

        return $this;
    }
}

src/Form/ActorType.php
<?php

namespace App\Form;

use App\Entity\Actor;
use App\Entity\Program;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class ActorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('birth_date')
            ->add('programs', EntityType::class, [
                'class' => Program::class,
                'choice_label' => 'title',
                'multiple' => true,
                'expanded' => false,
                'by_reference' => false,
            ])
            ->add('imageFile', VichFileType::class, ['label' => 'Photo']);


    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actor::class,
        ]);
    }
}

src/Controller/ActorController.php
<?php

namespace App\Controller;

use App\Entity\Actor;
use App\Form\ActorType;
use App\Repository\ActorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/actor')]
class ActorController extends AbstractController
{
    #[Route('/', name: 'app_actor_index', methods: ['GET'])]
    public function index(ActorRepository $actorRepository): Response
    {
        return $this->render('actor/index.html.twig', [
            'actors' => $actorRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_actor_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ActorRepository $actorRepository): Response
    {
        $actor = new Actor();
        $form = $this->createForm(ActorType::class, $actor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actorRepository->add($actor, true);

            return $this->redirectToRoute('app_actor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actor/new.html.twig', [
            'actor' => $actor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_actor_show', methods: ['GET'])]
    public function show(Actor $actor): Response
    {
        return $this->render('actor/show.html.twig', [
            'actor' => $actor,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_actor_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Actor $actor, ActorRepository $actorRepository): Response
    {
        $form = $this->createForm(ActorType::class, $actor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actorRepository->add($actor, true);

            return $this->redirectToRoute('app_actor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actor/edit.html.twig', [
            'actor' => $actor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_actor_delete', methods: ['POST'])]
    public function delete(Request $request, Actor $actor, ActorRepository $actorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$actor->getId(), $request->request->get('_token'))) {
            $actorRepository->remove($actor, true);
        }

        return $this->redirectToRoute('app_actor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/actor/_delete_form.html.twig
<form method="post" action="{{ path('app_actor_delete', {'id': actor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ actor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/actor/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/actor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Actor{% endblock %}

{% block body %}
    <h1>Edit Actor</h1>

    {{ include('actor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_actor_index') }}">back to list</a>

    {{ include('actor/_delete_form.html.twig') }}
{% endblock %}

templates/actor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actor index{% endblock %}

{% block body %}
    <h1>Actor index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Birth_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for actor in actors %}
            <tr>
                <td>{{ actor.id }}</td>
                <td>{{ actor.firstname }}</td>
                <td>{{ actor.lastname }}</td>
                <td>{{ actor.birthDate }}</td>
                <td>
                    <a href="{{ path('app_actor_show', {'id': actor.id}) }}">show</a>
                    <a href="{{ path('app_actor_edit', {'id': actor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_actor_new') }}">Create new</a>
{% endblock %}

templates/actor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Actor{% endblock %}

{% block body %}
    <h1>Create new Actor</h1>

    {{ include('actor/_form.html.twig') }}

    <a href="{{ path('app_actor_index') }}">back to list</a>
{% endblock %}

templates/actor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actor
{% endblock %}

{% block body %}
	<h1>Actor</h1>

	<table class="table">
		<tbody>
			{% if actor.image is not empty %}
				<tr>
					<th>Photo</th>
					<td><img src="{{ vich_uploader_asset(actor) }}" alt="" width='200px'></td>
				</tr>
			{% endif %}
			<tr>
				<th>Id</th>
				<td>{{ actor.id }}</td>
			</tr>
			<tr>
				<th>Firstname</th>
				<td>{{ actor.firstname }}</td>
			</tr>
			<tr>
				<th>Lastname</th>
				<td>{{ actor.lastname }}</td>
			</tr>
			<tr>
				<th>Birth_date</th>
				<td>{{ actor.birthDate }}</td>
			</tr>
			<tr>
				<th>Participation</th>
				<td>
					<ul>
						{% for program in actor.programs %}
							<a href="{{path('program_show', {slug: program.slug})}}">
								<li>{{program.title}}</li>
							</a>
						{% endfor %}
					</ul>
				</td>


			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_actor_index') }}">back to list</a>

	<a href="{{ path('app_actor_edit', {'id': actor.id}) }}">edit</a>

	{{ include('actor/_delete_form.html.twig') }}
{% endblock %}